<h3>La piscine ?</h3>
<p>42, c'est un <b>réseau d'écoles d'informatique</b> avce une pédagogie unique, très proche de celle d'Epitech (les mêmes personnes sont à la base de ces deux écoles). Il n'y a pas de profs, ni même de cours magistraux. Toutes les notions sont vues à travers des projets plus ou moins importants. L'école a une très bonne réputation au près des entreprises, et tous les élèves trouvent du travail au terme du cursus ou créent leur startup. Autre particularité de l'école, vous pouvez la faire à votre rythme. Certains travaillent même à coté. En bref, cette école offre énormement de libertés.</p>
<p>Pour rentrer dans cette école, pas d'entretien ou de concours classique. Les élèves sont séléctionnés grâce à la piscine : un mois de concours <b>très intense</b>. Vous allez enchaîner des projets de groupes, des projets individuels et des examens pour gagner des points. La piscine est une expérience inoubliable, tant par son intensité que par les rencontres que vous faites. L'ambiance est très bonne, et tout le monde s'entraide et se supporte.</p>
<p>L'organisation de la piscine et de l'école va essayer de vous noyer, c'est à dire que l'on vous donne aucune information et qu'il faudra aller checher vous même les informations. Il est inscrit à chaque début de sujet :</p>
<blockquote>Vous avez une question ? Demandez à votre voisin de droite. Sinon, essayez avec votre voisin de gauche.<br/>
Votre manuel de référence s'appelle Google / man / Internet...</blockquote>
<p>C'est pour ça que cet article ne vous donnera pas trop de détail, il faut garder le plaisir de la découverte et de la surprise de cet incroyable expérience.</p>
<p>Enfin, contrairement à l'école classique, 42 évolue beaucoup et très vite. Donc prenez mes conseils et mes informations avec des pincettes car elles pourraient ne plus être totalement valables lors de votre piscine. J'ai passé la mienne en Juillet 2019.</p>
<h3>Le contenu de la piscine</h3>
<p>Pendant la piscine comme pendant le cursus 42, vous avez un nombre de points d'expérience, et un niveau associé. Pendant la piscine, il y a plusieurs moyens de gagner des points.</p>
<p>Le plus important, ce sont les exercices que l'on vous donne à faire. Vous pouvez avancer à votre rythme sur ces petits projets, qui sont regroupés par notions. Il y a 15 modules qui contiennent chacun entre 4 et 18 exercices. Lors de ma piscine, seulement une trentaine de piscineux ont réussi à valider tous les modules. Donc si vous êtes un peu loin ne paniquez pas.</p>
<p>Il y a ensuite les exams. Ils ont lieu tous les vendredi soir. Ils durent tous 4h, sauf le dernier, l'exam final qui dure 8h. Ils valent plus de points que les modules, il est donc important de les valider ! Le premier examen est important, car plus d'un tier des participants ont 0. La raison ? Il est compliqué de se connecter en mode examen au macs, et la procédure n'est <b>jamais expliquée</b> ! Il est donc primordial avant le premier examen de se renseigner sur le fonctionnement de celui-ci.</p>
<p>Enfin, il y a les rush tous les weekends. Le sujet est divulgué le vendredi soir après l'exam, et le rendu se cloture le dimanche à 23h42. <b>Les groupes sont générés aléatoirement !</b> Il y a donc une petite part de chance avec les rush, et certains préfèrent ne pas s'incrire pour avancer sur les modules personnels. Il y a également le BSQ, un projet à deux. Cette fois vous pouvez choisir votre collègue, et il vaut autant de points que l'exam final ! Peu de groupes le tente, mais ceux qui le valident peuvent grandement améliorer leur chances d'être séléctionné.</p>
<h3>Être à l'aise avec un terminal</h3>
<p>Pendant la piscine, vous serez obligé d'utiliser le terminal de MacOS. Le terminal est une interface textuelle qui permet de donner des instructions à son ordinateur. Ce n'est vraiment pas compliqué de le maîtriser, mais cela prend un peu de temps et d'habitude. Maîtriser cet outil vous sauvera peut-être une journée ou deux. Je vous recommande au minimum :</p>
<ul>
    <li>De savoir se déplacer sur le disque. Voyez <b>les commandes cd, pwd, ls</b>. Vous pouvez commencer à vous entraîner chez vous si vous possédez un Mac, ou vous pouvez installer Linux qui possède un système similaire.</li>
    <li>De savoir manipuler des fichiers textes. Commencez avec les commandes <b>cat, tail, top, less</b>. Ensuite, il est très important de <b>maîtriser Vim</b>. Vim est un éditeur de texte en ligne de commande. Il est assez dur à utiliser pour un néophyte, donc soyez sur de bien le maîtriser avant de vous lancer.</li>
    <li>De comprendre les redirections avec les chevrons et les pipes.</li>
    <li>Moins indispensable mais toujours pratique, vous pouvez regarder les commandes top et apprendre à utiliser le multitâche dans le terminal.</li>
</ul>
<p>Les deux premiers modules de la piscine concernent le Shell, c'est le langage utilisé dans le terminal. Si vous avez déjà une petite base, vous pourrez passer ces deux modules assez rapidement et gagner du temps.</p>
<h3>Comprendre l'algorithmie de base</h3>
<p>Durant votre piscine vous apprendrez à programmer en C. Je ne pense pas qu'il soit indispensable de connaître le langage avant de faire la piscine. Cependant, les bases de l'algorithmie sont supposées acquises. Donc voyez :</p>
<ul>
    <li>Les boucles (surtout while, for est interdite en piscine)</li>
    <li>Les conditions</li>
    <li>Les fonctions</li>
    <li>La récursion</li>
</ul>
<p>Si vous avez bien assimilé ces notions, vous n'aurez pas trop de difficulté à programmer en C. Rappelez-vous qu'une bonne partie des piscineux n'ont jamais touché au code de leur vie. Cela reste donc accessible.</p>
<h3>Se préparer à la vie de l'école</h3>
<p>Une des choses à éviter durant la piscine, ce sont les TIG, travaux d'intérets généraux. Ils durent de 2h à 8h, et vous feront perdre un temps précieux. Il est donc très important de bien lire le réglement avant de commencer à travailler. Une des raisons de se prendre une TIG, c'est de brancher un cable Jack sur les Macs. Cela peut abîmer l'ordinateur sur le long terme et 42 souhaite vraiment les conserver le plus longtemps possible. Il est donc essentiel d'avoir <b>un casque bluetooth</b>, ou <b>un adaptateur Jack-USB</b>. Ces derniers peuvent être prétés par l'école mais il n'y en a qu'un nombre limité.<br />Mettre une bouteille d'eau sur une table est également un motif de TIG, donc essayer de casser cette habitude.</p>
<h3>La piscine est une expérience incroyable</h3>
<p>Dans tous les cas, la piscine sera une expérience très enrichissante. De toutes les personnes que j'ai pu cotoyer durant ce mois intensif, toutes étaient très heureuses d'avoir participé à cette expérience. Si vous ne savez pas coder, vous allez apprendre énormément. En un mois de piscine vous pourrez faire selon votre rythme de travail autant de pratique qu'en 1 an de fac. Si vous savez déjà coder vous apprendrez à avoir une rigueur extrême et vous approfondirez des notions comme la récursivité. De plus, vous ferez beaucoup de rencontres, l'ambiance étant excellente !<br />Bref, si vous allez faire votre piscine, mouillez-vous la nuque et plongez !</p>
